from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(975, 545)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 170, 160, 113))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(20, 10, 160, 61))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.user_label = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.user_label.setObjectName("user_label")
        self.gridLayout_2.addWidget(self.user_label, 0, 0, 1, 1)
        self.sample_label = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.sample_label.setObjectName("sample_label")
        self.gridLayout_2.addWidget(self.sample_label, 1, 0, 1, 1)
        self.user_input = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.user_input.setObjectName("user_input")
        self.gridLayout_2.addWidget(self.user_input, 0, 1, 1, 1)
        self.user_input_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.user_input_2.setObjectName("user_input_2")
        self.gridLayout_2.addWidget(self.user_input_2, 1, 1, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 90, 160, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.src_sns_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.src_sns_grid.setContentsMargins(0, 0, 0, 0)
        self.src_sns_grid.setObjectName("src_sns_grid")
        self.sns_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.sns_comboBox.setObjectName("sns_comboBox")
        self.sns_comboBox.addItem("")
        self.sns_comboBox.addItem("")
        self.sns_comboBox.addItem("Resistance")
        self.src_sns_grid.addWidget(self.sns_comboBox, 1, 1, 1, 1)
        self.src_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.src_comboBox.setObjectName("src_comboBox")
        self.src_comboBox.addItem("")
        self.src_comboBox.addItem("")
        self.src_comboBox.addItem("Resistance")
        self.src_comboBox.setCurrentIndex(1)
        self.src_sns_grid.addWidget(self.src_comboBox, 0, 1, 1, 1)
        self.sns_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.sns_label.setObjectName("sns_label")
        self.src_sns_grid.addWidget(self.sns_label, 1, 0, 1, 1)
        self.src_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.src_label.setObjectName("src_label")
        self.src_sns_grid.addWidget(self.src_label, 0, 0, 1, 1)
        self.range_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.range_grid.setContentsMargins(0, 0, 0, 0)
        self.range_grid.setObjectName("range_grid")
        self.start_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.start_label.setObjectName("start_label")
        self.range_grid.addWidget(self.start_label, 1, 0, 1, 1)
        self.step_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.step_label.setObjectName("step_label")
        self.range_grid.addWidget(self.step_label, 2, 0, 1, 1)
        self.stop_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.stop_label.setObjectName("stop_label")
        self.range_grid.addWidget(self.stop_label, 3, 0, 1, 1)
        self.start_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.start_input.setObjectName("start_input")
        self.start_input.setText("0")
        self.range_grid.addWidget(self.start_input, 1, 1, 1, 1)
        self.step_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.step_input.setObjectName("step_input")
        self.step_input.setText("0.5")
        self.range_grid.addWidget(self.step_input, 2, 1, 1, 1)
        self.stop_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.stop_input.setObjectName("stop_input")
        self.stop_input.setText("1")
        self.range_grid.addWidget(self.stop_input, 3, 1, 1, 1)
        self.range_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.range_label.setAlignment(QtCore.Qt.AlignCenter)
        self.range_label.setObjectName("range_label")
        self.range_grid.addWidget(self.range_label, 0, 0, 1, 3)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(200, 210, 160, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.wire_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.wire_grid.setContentsMargins(0, 0, 0, 0)
        self.wire_grid.setObjectName("wire_grid")
        self.w4_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.w4_rbtn.setObjectName("w4_rbtn")
        self.wire_grid.addWidget(self.w4_rbtn, 2, 0, 1, 1)
        self.w2_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.w2_rbtn.setObjectName("w2_rbtn")
        self.w2_rbtn.setChecked(True)
        self.wire_grid.addWidget(self.w2_rbtn, 1, 0, 1, 1)
        self.wire_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.wire_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wire_label.setObjectName("wire_label")
        self.wire_grid.addWidget(self.wire_label, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(200, 110, 160, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.panel_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.panel_grid.setContentsMargins(0, 0, 0, 0)
        self.panel_grid.setObjectName("panel_grid")
        self.panel_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.panel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.panel_label.setObjectName("panel_label")
        self.panel_grid.addWidget(self.panel_label, 0, 0, 1, 1)
        self.rear_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.rear_rbtn.setObjectName("rear_rbtn")
        self.panel_grid.addWidget(self.rear_rbtn, 2, 0, 1, 1)
        self.front_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.front_rbtn.setObjectName("front_rbtn")
        self.front_rbtn.setChecked(True)
        self.panel_grid.addWidget(self.front_rbtn, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 300, 160, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.compliance_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.compliance_grid.setContentsMargins(0, 0, 0, 0)
        self.compliance_grid.setObjectName("compliance_grid")
        self.comp_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.comp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp_label.setObjectName("comp_label")
        self.compliance_grid.addWidget(self.comp_label, 0, 0, 1, 2)
        self.comp_input = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.comp_input.setInputMask("")
        self.comp_input.setText("100e-3")
        self.comp_input.setObjectName("comp_input")
        self.compliance_grid.addWidget(self.comp_input, 1, 0, 1, 1)
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(20, 370, 160, 23))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.compliance_grid_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.compliance_grid_2.setContentsMargins(0, 0, 0, 0)
        self.compliance_grid_2.setObjectName("compliance_grid_2")
        self.delay_input = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.delay_input.setText("0")
        self.delay_input.setObjectName("delay_input")
        self.compliance_grid_2.addWidget(self.delay_input, 1, 1, 1, 1)
        self.comp_label_2 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.comp_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.comp_label_2.setObjectName("comp_label_2")
        self.compliance_grid_2.addWidget(self.comp_label_2, 1, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 410, 160, 21))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.repetition_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.repetition_grid.setContentsMargins(0, 0, 0, 0)
        self.repetition_grid.setObjectName("repetition_grid")
        self.repet_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.repet_label.setAlignment(QtCore.Qt.AlignCenter)
        self.repet_label.setObjectName("repet_label")
        self.repetition_grid.addWidget(self.repet_label, 0, 0, 1, 1)
        self.repet_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.repet_spinBox.setMinimum(1)
        self.repet_spinBox.setMaximum(10)
        self.repet_spinBox.setObjectName("repet_spinBox")
        self.repetition_grid.addWidget(self.repet_spinBox, 0, 1, 1, 1)
        self.MplWidget = pg.PlotWidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(390, 0, 581, 541))
        self.MplWidget.setObjectName("MplWidget")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(180, 0, 20, 501))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(200, 310, 160, 59))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.power_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.power_grid.setContentsMargins(0, 0, 0, 0)
        self.power_grid.setObjectName("power_grid")
        self.pwr_off_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.pwr_off_btn.setObjectName("pwr_off_btn")
        self.power_grid.addWidget(self.pwr_off_btn, 1, 1, 1, 1)
        self.pwr_on_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.pwr_on_btn.setObjectName("pwr_on_btn")
        self.power_grid.addWidget(self.pwr_on_btn, 1, 0, 1, 1)
        self.pwr_label = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.pwr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pwr_label.setObjectName("pwr_label")
        self.power_grid.addWidget(self.pwr_label, 0, 0, 1, 2)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(200, 390, 160, 51))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.conn_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.conn_grid.setContentsMargins(0, 0, 0, 0)
        self.conn_grid.setObjectName("conn_grid")
        self.conn_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.conn_label.setAlignment(QtCore.Qt.AlignCenter)
        self.conn_label.setObjectName("conn_label")
        self.conn_grid.addWidget(self.conn_label, 1, 0, 1, 1)
        self.conn_btn = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.conn_btn.setObjectName("conn_btn")
        self.conn_grid.addWidget(self.conn_btn, 2, 0, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(20, 460, 341, 43))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.action_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.action_grid.setContentsMargins(0, 0, 0, 0)
        self.action_grid.setObjectName("action_grid")
        self.run_btn = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.run_btn.setObjectName("run_btn")
        self.action_grid.addWidget(self.run_btn, 0, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.save_btn.setObjectName("save_btn")
        self.action_grid.addWidget(self.save_btn, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(370, 0, 20, 541))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(200, 10, 161, 31))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.user_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.user_grid.setContentsMargins(0, 0, 0, 0)
        self.user_grid.setObjectName("user_grid")
        self.date_label = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.date_label.setObjectName("date_label")
        self.user_grid.addWidget(self.date_label, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.user_grid.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.user_grid.addItem(spacerItem1, 1, 4, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 510, 341, 23))
        self.progressBar.setObjectName("progressBar")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(200, 60, 161, 31))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.measure_type = QtWidgets.QComboBox(self.gridLayoutWidget_12)
        self.measure_type.setObjectName("comboBox")
        self.measure_type.addItem("")
        self.measure_type.addItem("")
        self.measure_type.setCurrentIndex(0)
        self.gridLayout.addWidget(self.measure_type, 0, 1, 1, 1)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.menuMenu.addAction(self.actionOpen)
        self.menuMenu.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionSobre)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.range_label.setText(_translate("MainWindow", "Measure Range"))
        self.stop_label.setText(_translate("MainWindow", "Stop"))
        self.step_label.setText(_translate("MainWindow", "Step"))
        self.start_label.setText(_translate("MainWindow", "Start"))
        self.w4_rbtn.setText(_translate("MainWindow", "4 Wire Mode"))
        self.w2_rbtn.setText(_translate("MainWindow", "2 Wire Mode"))
        self.wire_label.setText(_translate("MainWindow", "Select Wire Mode"))
        self.panel_label.setText(_translate("MainWindow", "Select Panel"))
        self.rear_rbtn.setText(_translate("MainWindow", "Rear Terminal"))
        self.front_rbtn.setText(_translate("MainWindow", "Front Terminal"))
        self.comp_label.setText(_translate("MainWindow", "Compliance"))
        self.sns_comboBox.setItemText(0, _translate("MainWindow", "Current"))
        self.sns_comboBox.setItemText(1, _translate("MainWindow", "Voltage"))
        self.src_comboBox.setItemText(0, _translate("MainWindow", "Current"))
        self.src_comboBox.setItemText(1, _translate("MainWindow", "Voltage"))
        self.sns_label.setText(_translate("MainWindow", "Sense"))
        self.src_label.setText(_translate("MainWindow", "Source"))
        self.repet_label.setText(_translate("MainWindow", "Repetitions"))
        self.pwr_off_btn.setText(_translate("MainWindow", "OFF"))
        self.pwr_on_btn.setText(_translate("MainWindow", "ON"))
        self.pwr_label.setText(_translate("MainWindow", "Keithley Test"))
        self.conn_label.setText(_translate("MainWindow", "Connection Test"))
        self.conn_btn.setText(_translate("MainWindow", "Check Connection"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.date_label.setText(_translate("MainWindow", "Datetime"))
        self.delay_input.setInputMask(_translate("MainWindow", "0"))
        self.comp_label_2.setText(_translate("MainWindow", "Delay"))
        self.label.setText(_translate("MainWindow", "Type"))
        self.measure_type.setItemText(0, _translate("MainWindow", "IV"))
        self.measure_type.setItemText(1, _translate("MainWindow", "Fixed Voltage"))
        self.user_label.setText(_translate("MainWindow", "Username"))
        self.sample_label.setText(_translate("MainWindow", "Sample"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
