from PyQt5 import QtCore, QtGui, QtWidgets
from GUI.mplwidget import MplWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(960, 540)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 130, 160, 98))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.range_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.range_grid.setContentsMargins(0, 0, 0, 0)
        self.range_grid.setObjectName("range_grid")
        self.step_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.step_label.setObjectName("step_label")
        self.range_grid.addWidget(self.step_label, 2, 0, 1, 1)
        self.step_unit_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.step_unit_label.setObjectName("step_unit_label")
        self.range_grid.addWidget(self.step_unit_label, 2, 2, 1, 1)
        self.stop_unit_label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.stop_unit_label_4.setObjectName("stop_unit_label_4")
        self.range_grid.addWidget(self.stop_unit_label_4, 3, 2, 1, 1)
        self.start_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.start_label.setObjectName("start_label")
        self.range_grid.addWidget(self.start_label, 1, 0, 1, 1)
        self.step_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.step_input.setObjectName("step_input")
        self.range_grid.addWidget(self.step_input, 2, 1, 1, 1)
        self.stop_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.stop_label.setObjectName("stop_label")
        self.range_grid.addWidget(self.stop_label, 3, 0, 1, 1)
        self.start_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.start_input.setObjectName("start_input")
        self.range_grid.addWidget(self.start_input, 1, 1, 1, 1)
        self.stop_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.stop_input.setObjectName("stop_input")
        self.range_grid.addWidget(self.stop_input, 3, 1, 1, 1)
        self.start_unit_label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.start_unit_label_3.setObjectName("start_unit_label_3")
        self.range_grid.addWidget(self.start_unit_label_3, 1, 2, 1, 1)
        self.range_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.range_label.setAlignment(QtCore.Qt.AlignCenter)
        self.range_label.setObjectName("range_label")
        self.range_grid.addWidget(self.range_label, 0, 0, 1, 3)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(190, 130, 160, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.wire_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.wire_grid.setContentsMargins(0, 0, 0, 0)
        self.wire_grid.setObjectName("wire_grid")
        self.w4_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.w4_rbtn.setObjectName("w4_rbtn")
        self.wire_grid.addWidget(self.w4_rbtn, 2, 0, 1, 1)
        self.w2_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.w2_rbtn.setObjectName("w2_rbtn")
        self.wire_grid.addWidget(self.w2_rbtn, 1, 0, 1, 1)
        self.wire_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.wire_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wire_label.setObjectName("wire_label")
        self.wire_grid.addWidget(self.wire_label, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(190, 20, 160, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.panel_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.panel_grid.setContentsMargins(0, 0, 0, 0)
        self.panel_grid.setObjectName("panel_grid")
        self.panel_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.panel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.panel_label.setObjectName("panel_label")
        self.panel_grid.addWidget(self.panel_label, 0, 0, 1, 1)
        self.rear_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.rear_rbtn.setObjectName("rear_rbtn")
        self.panel_grid.addWidget(self.rear_rbtn, 2, 0, 1, 1)
        self.front_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.front_rbtn.setObjectName("front_rbtn")
        self.panel_grid.addWidget(self.front_rbtn, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 310, 160, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.compliance_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.compliance_grid.setContentsMargins(0, 0, 0, 0)
        self.compliance_grid.setObjectName("compliance_grid")
        self.comp_input = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.comp_input.setObjectName("comp_input")
        self.compliance_grid.addWidget(self.comp_input, 1, 0, 1, 1)
        self.comp_unit_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.comp_unit_label.setObjectName("comp_unit_label")
        self.compliance_grid.addWidget(self.comp_unit_label, 1, 1, 1, 1)
        self.comp_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.comp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comp_label.setObjectName("comp_label")
        self.compliance_grid.addWidget(self.comp_label, 0, 0, 1, 2)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 160, 80))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.src_sns_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.src_sns_grid.setContentsMargins(0, 0, 0, 0)
        self.src_sns_grid.setObjectName("src_sns_grid")
        self.sns_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.sns_comboBox.setObjectName("sns_comboBox")
        self.sns_comboBox.addItem("")
        self.sns_comboBox.addItem("")
        self.src_sns_grid.addWidget(self.sns_comboBox, 1, 1, 1, 1)
        self.src_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.src_comboBox.setObjectName("src_comboBox")
        self.src_comboBox.addItem("")
        self.src_comboBox.addItem("")
        self.src_sns_grid.addWidget(self.src_comboBox, 0, 1, 1, 1)
        self.sns_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.sns_label.setObjectName("sns_label")
        self.src_sns_grid.addWidget(self.sns_label, 1, 0, 1, 1)
        self.src_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.src_label.setObjectName("src_label")
        self.src_sns_grid.addWidget(self.src_label, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 250, 160, 31))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.repetition_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.repetition_grid.setContentsMargins(0, 0, 0, 0)
        self.repetition_grid.setObjectName("repetition_grid")
        self.repet_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.repet_label.setAlignment(QtCore.Qt.AlignCenter)
        self.repet_label.setObjectName("repet_label")
        self.repetition_grid.addWidget(self.repet_label, 0, 0, 1, 1)
        self.repet_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.repet_spinBox.setMinimum(1)
        self.repet_spinBox.setMaximum(10)
        self.repet_spinBox.setObjectName("repet_spinBox")
        self.repetition_grid.addWidget(self.repet_spinBox, 0, 1, 1, 1)
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(378, 0, 571, 511))
        self.MplWidget.setObjectName("MplWidget")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 0, 20, 511))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(190, 240, 160, 51))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.power_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.power_grid.setContentsMargins(0, 0, 0, 0)
        self.power_grid.setObjectName("power_grid")
        self.pwr_off_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.pwr_off_btn.setObjectName("pwr_off_btn")
        self.power_grid.addWidget(self.pwr_off_btn, 1, 1, 1, 1)
        self.pwr_on_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.pwr_on_btn.setObjectName("pwr_on_btn")
        self.power_grid.addWidget(self.pwr_on_btn, 1, 0, 1, 1)
        self.pwr_label = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.pwr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pwr_label.setObjectName("pwr_label")
        self.power_grid.addWidget(self.pwr_label, 0, 0, 1, 2)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(190, 320, 160, 51))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.conn_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.conn_grid.setContentsMargins(0, 0, 0, 0)
        self.conn_grid.setObjectName("conn_grid")
        self.conn_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.conn_label.setAlignment(QtCore.Qt.AlignCenter)
        self.conn_label.setObjectName("conn_label")
        self.conn_grid.addWidget(self.conn_label, 1, 0, 1, 1)
        self.conn_btn = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.conn_btn.setObjectName("conn_btn")
        self.conn_grid.addWidget(self.conn_btn, 2, 0, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(-1, 470, 361, 31))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.action_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.action_grid.setContentsMargins(0, 0, 0, 0)
        self.action_grid.setObjectName("action_grid")
        self.save_btn = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.save_btn.setObjectName("save_btn")
        self.action_grid.addWidget(self.save_btn, 0, 0, 1, 1)
        self.run_btn = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.run_btn.setObjectName("run_btn")
        self.action_grid.addWidget(self.run_btn, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(360, 0, 20, 511))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.menuMenu.addAction(self.actionOpen)
        self.menuMenu.addAction(self.actionSave)
        self.menuMenu.addAction(self.actionSobre)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.step_label.setText(_translate("MainWindow", "Step"))
        self.step_unit_label.setText(_translate("MainWindow", "mA"))
        self.stop_unit_label_4.setText(_translate("MainWindow", "mA"))
        self.start_label.setText(_translate("MainWindow", "Start"))
        self.stop_label.setText(_translate("MainWindow", "Stop"))
        self.start_unit_label_3.setText(_translate("MainWindow", "mA"))
        self.range_label.setText(_translate("MainWindow", "Set range"))
        self.w4_rbtn.setText(_translate("MainWindow", "4 Wire Mode"))
        self.w2_rbtn.setText(_translate("MainWindow", "2 Wire Mode"))
        self.wire_label.setText(_translate("MainWindow", "Select Wire Mode"))
        self.panel_label.setText(_translate("MainWindow", "Select Panel"))
        self.rear_rbtn.setText(_translate("MainWindow", "Rear Terminal"))
        self.front_rbtn.setText(_translate("MainWindow", "Front Terminal"))
        self.comp_input.setInputMask(_translate("MainWindow", "100E-3"))
        self.comp_input.setText(_translate("MainWindow", "100E-3"))
        self.comp_unit_label.setText(_translate("MainWindow", "mA"))
        self.comp_label.setText(_translate("MainWindow", "Set compliance"))
        self.sns_comboBox.setItemText(0, _translate("MainWindow", "Current"))
        self.sns_comboBox.setItemText(1, _translate("MainWindow", "Voltage"))
        self.src_comboBox.setItemText(0, _translate("MainWindow", "Current"))
        self.src_comboBox.setItemText(1, _translate("MainWindow", "Voltage"))
        self.sns_label.setText(_translate("MainWindow", "Sense"))
        self.src_label.setText(_translate("MainWindow", "Source"))
        self.repet_label.setText(_translate("MainWindow", "Repetitions"))
        self.pwr_off_btn.setText(_translate("MainWindow", "OFF"))
        self.pwr_on_btn.setText(_translate("MainWindow", "ON"))
        self.pwr_label.setText(_translate("MainWindow", "Keithley Test"))
        self.conn_label.setText(_translate("MainWindow", "Connection Test"))
        self.conn_btn.setText(_translate("MainWindow", "Check Connection"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
